version: "3"

http:
  address: 127.0.0.1:8080
  workers:
    command: "php micro.php"
    pool:
      num_workers: 4 # Adjust as needed
static:
    dir:   public
    forbid:
      - .php
      - .htaccess
logs:
    mode: "development"  # Set logging mode to "development"
    level: "debug"       # Set logging level to "debug"